######################################################################
# Automatically generated by qmake (2.01a) Fri Oct 5 08:37:10 2012
######################################################################

TEMPLATE = app
TARGET = Example
DEPENDPATH += .
INCLUDEPATH += .

# Input
HEADERS += example.h labelbutton.h
SOURCES += example.cpp labelbutton.cpp main.cpp
RESOURCES += resources.qrc

QT += core gui
